AVL-Tree code
OwlusMain/avltree pull request #1
Opened 2019-06-23 22:09 UTC by OwlusMain

2019-06-24 07:39 UTC, Skird requested changes

2019-06-24 07:39 UTC, Skird commented on amic5.cpp
> +            node(ValueType val = ValueType()) : key(val), height(1), leftNode(nullptr), rightNode(nullptr), parentNode(nullptr) {}
Стоит помечать конструкторы от 1 переменной как `explicit`

2019-06-24 07:39 UTC, Skird commented on amic5.cpp
> +                return new node(newKey);
Опасность.
Увы, new всегда может бросить исключение и с этим ничего не поделать.
В целом, не ловить его - это нормально, но поскольку эта штука вызывается в конструкторе возможны красивые сценарии утечки: пользователь копирует структуру конструктором копирования, у него кончается память в процессе. Бросается exception, который он ловит, понимает, что памяти-то много, что-то там чистит и работает дальше. Но есть один нюанс: из конструктора было брошено исключение, поэтому деструктор вызван не будет (объект не сконструировался). Память утекла, потому что в рекурсии было много успешных вызовов new.
Можно поиграть локально запуская процесс, после команды `ulimit -Sv 100000` (ML 100 Mb, правда не работает в сочетании с valgrind и asan по понятным причинам)

2019-06-24 07:39 UTC, Skird commented on amic5.cpp
> +                insert(*first);
Потенциальная утечка (см. большой комментарий)

2019-06-25 23:03 UTC, OwlusMain commented on amic5.cpp
> +                return new node(newKey);
Да, согласен, исправлю

2019-06-25 23:03 UTC, OwlusMain commented on amic5.cpp
> +                insert(*first);
Как раз-таки все конструкторы в конечном итоге вызывают этот, поэтому в нем утечку исправил

2019-06-26 10:36 UTC, Skird requested changes
Кажется, неправильный фикс

2019-06-26 10:36 UTC, Skird commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
Тут проблема все еще осталась: при выбросе исключения в рекурсии leftNode не присвоится и дерево может стать каким-то несвязным или некорректным
Не очень очевидно, как это будет работать. Скорее всего надо ловить исключение прямо в рекурсии и обрабатывать
P.S. всего этого можно было бы избежать, использовав `std::unique_ptr` и `std::make_unique`. Рекомендую **никогда** не использовать сырые `new/delete` без крайней необходимости

2019-06-26 13:01 UTC, OwlusMain commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
а он разве не пробросит исключение дальше, не осуществив операцию присвоения? Структура дерева же при этом не меняется - поэтому вроде все нормально работает

> P.S. всего этого можно было бы избежать, использовав std::unique_ptr и std::make_unique. Рекомендую никогда не использовать сырые new/delete без крайней необходимости

у меня на вершину в дереве из двух вершин сразу есть указатели, которые я смотрю. Поэтому есть ли смысл в unique_ptr?
Можно, конечно, shared_ptr использовать в такой ситуации. Но опять же: раз у меня две вершины ссылаются друг на друга, то придется все равно руками чистить память

А так да - умные указатели я по возможности стараюсь всегда использовать

2019-06-26 13:16 UTC, OwlusMain commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
Проверил - присвоения в результате exception не происходит
Подправлю, поэтому чуть код, чтобы совсем уж у компилятора недопониманий не возникало. Но мне до сих пор кажется, что исключение будет проброшено дальше и конкретно здесь ничего не изменится

2019-06-26 13:26 UTC, OwlusMain commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
А, я понял, в чем здесь еще проблема: если не ловить исключение при создании нового элемента, то sz изменится, а элемент создан не будет. Сейчас исправлю

2019-06-27 09:03 UTC, Skird commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
Дело в том, что smart pointer нужен для того, чтобы отслеживать ownership. Это важно понимать, если у меня есть unique_ptr, то я owner объекта. В дереве довольно понятно, что ownership над сыновьями принадлежит родителям. А другие ссылки (как ссылка на предка, которая не подразумевает ownership) можно оставить обычными сырыми указателями (но не использовать new/delete при этом). Альтернативный вариант - shared_ptr, но у него тоже есть свои тонкости, размывается ownership + performance уже может проседать ощутимее

2019-06-27 09:05 UTC, Skird commented on amic5.cpp
> +                curNode->leftNode = InsertImpl(curNode->leftNode, newKey);
Да, я осознал, в целом фикс верный, потому что сначала создается нода, потом делаются все изменения в дереве.

2019-06-27 09:06 UTC, merged